title: Mohammad Nuruddin Effendi
baseurl: ""
theme: "jekyll-theme-minimal-resume"
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - crisp-minimal-resume.gemspec
  - /script
  - /screenshots
  - /fixtures
